[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'No build step needed'"

[[redirects]]
  from = "/booking-confirmed"
  to = "/booking-confirmed.html"
  status = 200

[[redirects]]
  from = "/booking-cancelled"
  to = "/booking-cancelled.html"
  status = 200

[[redirects]]
  from = "/delegate-form"
  to = "/delegate-form.html"
  status = 200

[[redirects]]
  from = "/leaderboard"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/hrd-corp-claims"
  to = "/hrd-corp-claims.html"
  status = 200

[[redirects]]
  from = "/hrd-corp-eligibility"
  to = "/hrd-corp-eligibility.html"
  status = 200

[functions."send-sales-reports"]
  schedule = "0 1 * * *"

[functions."check-cohort-minimums"]
  schedule = "0 2 * * *"

[functions."send-ops-planning-report"]
  schedule = "0 3 * * *"

[functions."issue-self-credits"]
  schedule = "0 4 * * *"
